export function configurationPage() {
  return `<!doctype html>
<html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Beepster settings</title><style>
:root{color-scheme:dark;font:17px system-ui}*{box-sizing:border-box}body{max-width:38rem;margin:0 auto;padding:22px;background:#101820;color:#f7fbff}
h1{margin-bottom:5px;color:#55d6be}h2{margin:28px 0 8px;font-size:1.08rem}label{display:block;margin:15px 0 6px}.hint{color:#b7c7d4;font-size:.9rem}.error{color:#ff9c9c}
input,select,button{width:100%;font:inherit;padding:11px;border-radius:10px;border:1px solid #789;background:#172633;color:inherit}button{border:0;background:#55d6be;color:#07120f;font-weight:700}.secondary{background:#314555;color:#fff}.danger{background:#742f3a;color:#fff}
.row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.buttons{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.swatches{display:grid;grid-template-columns:1fr 1fr;gap:10px}.swatches label{margin-top:10px}.swatches input{height:46px;padding:4px}.services{display:grid;grid-template-columns:1fr 1fr;gap:2px 14px}.services label{display:flex;align-items:center;gap:9px;margin:7px 0}.services input{width:auto;accent-color:#55d6be}.apple-links{display:grid;gap:10px}.apple-link{padding:11px;border:1px solid #496171;border-radius:10px}.apple-link label{margin:0 0 7px;overflow-wrap:anywhere}.apple-link input{padding:9px}
#preview{margin:16px 0;padding:13px;border-radius:12px;min-height:132px}.preview-title{font-size:1.2rem;font-weight:700}.preview-body{margin-top:9px}.preview-muted{margin-top:9px;font-size:.85rem}.preview-button{display:inline-block;margin-top:12px;padding:6px 10px;border-radius:7px;font-weight:700}
#save{margin-top:22px}.hidden{display:none}</style></head>
<body><h1>Beepster</h1><p id="intro">Pair this Pebble with your private Mac companion.</p>
<form id="form"><div id="pairing"><label>One-time pairing code</label><input id="code" inputmode="numeric" autocomplete="one-time-code"></div>
<h2>Saved themes</h2><label for="theme">Theme</label><select id="theme"></select>
<div class="buttons"><button type="button" id="newTheme" class="secondary">New custom theme</button><button type="button" id="deleteTheme" class="danger">Delete custom theme</button></div>
<p class="hint" id="deleteHint">Built-in themes cannot be deleted.</p>
<div id="preview"><div class="preview-title">Beepster preview</div><div class="preview-body">Alex: Dinner at seven? 😃</div><div class="preview-muted">2 minutes ago</div><div class="preview-button">Reply</div></div>
<h2>Theme editor</h2><label for="themeName">Theme name</label><input id="themeName" maxlength="32">
<div class="swatches"><label>Background<input type="color" id="background"></label><label>Text<input type="color" id="text"></label><label>Muted text<input type="color" id="muted"></label><label>Accent<input type="color" id="accent"></label><label>Accent text<input type="color" id="accentText"></label></div>
<div class="row"><label>Font<select id="font"><option value="inter">Inter</option><option value="roboto">Roboto</option><option value="open-sans">Open Sans</option><option value="montserrat">Montserrat</option><option value="poppins">Poppins</option></select></label><label>Font size<select id="size"><option value="14">14</option><option value="18">18</option><option value="22">22</option><option value="26">26</option><option value="30">30</option></select></label></div>
<h2>Quick replies</h2><p class="hint">Add up to eight replies. Text and emoji are sent exactly as entered; leave unused slots blank.</p><div id="quickReplies"></div>
<h2>Included services</h2><p class="hint">Choose which services appear in the watch inbox. Changes apply without pairing again.</p><div id="services" class="services"></div>
<h2>Link Apple conversations</h2><p class="hint">If Apple Messages exposes the same person as separate email and phone chats, enter the same contact name beside both. Beepster will combine their history on the watch while preserving both Beeper destinations.</p><div id="appleLinks" class="apple-links"></div><p id="appleLinksEmpty" class="hint">No recent Apple conversations are available yet. Open the Beepster inbox once, then return to Settings.</p>
<label>Refresh interval</label><select id="refresh"><option value="60">1 minute</option><option value="180">3 minutes</option><option value="300">5 minutes</option><option value="0">Manual only</option></select>
<button id="save">Test connection &amp; pair</button><p id="status" class="hint">The code can be viewed or rotated on your Mac.</p></form>
<script>
const f=document.getElementById('form'),s=document.getElementById('status'),themeSelect=document.getElementById('theme');let initial={};
try{initial=JSON.parse(decodeURIComponent(location.hash.slice(1)||'%7B%7D'));}catch(e){}
const defaults=[
{id:'classic',name:'Classic',background:'#FFFFFF',text:'#000000',muted:'#555555',accent:'#0055AA',accentText:'#FFFFFF',font:'inter',size:22,builtIn:true},
{id:'dark',name:'Midnight',background:'#000000',text:'#FFFFFF',muted:'#AAAAAA',accent:'#00AAFF',accentText:'#000000',font:'roboto',size:22,builtIn:true},
{id:'ocean',name:'Ocean',background:'#001133',text:'#FFFFFF',muted:'#AAFFFF',accent:'#00AAFF',accentText:'#000000',font:'roboto',size:22,builtIn:true},
{id:'contrast',name:'High Contrast',background:'#FFFFFF',text:'#000000',muted:'#000000',accent:'#000000',accentText:'#FFFFFF',font:'open-sans',size:26,builtIn:true},
{id:'plum',name:'Plum',background:'#330033',text:'#FFFFFF',muted:'#FFAAFF',accent:'#AA00AA',accentText:'#FFFFFF',font:'poppins',size:30,builtIn:true},
{id:'forest',name:'Forest',background:'#003300',text:'#FFFFFF',muted:'#AAFFAA',accent:'#00AA55',accentText:'#000000',font:'open-sans',size:26,builtIn:true}
];
const fields=['themeName','background','text','muted','accent','accentText','font','size'];
const quickDefaults=['Yes','No','On my way','Thanks! 👍'],quickSource=Array.isArray(initial.quickReplies)?initial.quickReplies:quickDefaults,quickContainer=document.getElementById('quickReplies');
for(let i=0;i<8;i++){const label=document.createElement('label'),input=document.createElement('input');label.textContent='Quick reply '+(i+1);input.id='quickReply'+i;input.maxLength=240;input.placeholder=i<quickDefaults.length?quickDefaults[i]:'Optional';input.value=quickSource[i]||'';label.appendChild(input);quickContainer.appendChild(label);}
const serviceOptions=[['apple_messages','Apple Messages'],['beeper','Beeper / Matrix'],['discord','Discord'],['google_chat','Google Chat'],['google_messages','Google Messages'],['google_voice','Google Voice'],['instagram','Instagram'],['line','LINE'],['linkedin','LinkedIn'],['messenger','Messenger'],['signal','Signal'],['slack','Slack'],['telegram','Telegram'],['x','X / Twitter'],['whatsapp','WhatsApp'],['other','Other services']],enabledSource=Array.isArray(initial.services)?initial.services:null,serviceContainer=document.getElementById('services');
serviceOptions.forEach(option=>{const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.value=option[0];input.checked=!enabledSource||enabledSource.includes(option[0]);label.appendChild(input);label.appendChild(document.createTextNode(option[1]));serviceContainer.appendChild(label);});
const appleAliases=initial.appleAliases&&typeof initial.appleAliases==='object'?initial.appleAliases:{},appleCandidates=Array.isArray(initial.appleCandidates)?initial.appleCandidates:[],appleLinks=document.getElementById('appleLinks');
appleCandidates.forEach(candidate=>{if(!candidate||!candidate.id)return;const box=document.createElement('div'),label=document.createElement('label'),input=document.createElement('input');box.className='apple-link';label.textContent=candidate.label||'Apple conversation';input.placeholder='Contact name (optional)';input.maxLength=56;input.value=appleAliases[candidate.id]||candidate.alias||'';input.dataset.chatId=candidate.id;box.appendChild(label);box.appendChild(input);appleLinks.appendChild(box);});document.getElementById('appleLinksEmpty').className=appleCandidates.length?'hidden':'hint';
let themes=defaults.concat((initial.themes||[]).filter(t=>!t.builtIn&&!defaults.some(d=>d.id===t.id))).slice(0,26),currentId=(initial.theme&&initial.theme.id)||'classic';
function selected(){return themes.find(t=>t.id===currentId)||themes[0];}
function renderOptions(){themeSelect.innerHTML='';themes.forEach(t=>{const o=document.createElement('option');o.value=t.id;o.textContent=(t.builtIn?'Preset — ':'Custom — ')+t.name;themeSelect.appendChild(o);});themeSelect.value=currentId;}
function loadEditor(){const t=selected();document.getElementById('themeName').value=t.name;['background','text','muted','accent','accentText','font','size'].forEach(k=>document.getElementById(k).value=t[k]);document.getElementById('deleteTheme').disabled=Boolean(t.builtIn);renderPreview();}
function renderPreview(){const t=selected(),p=document.getElementById('preview'),families={inter:'Inter,Arial,sans-serif',roboto:'Roboto,Arial,sans-serif','open-sans':'Open Sans,Arial,sans-serif',montserrat:'Montserrat,Arial,sans-serif',poppins:'Poppins,Arial,sans-serif'};p.style.background=t.background;p.style.color=t.text;p.style.fontFamily=families[t.font]||families.inter;p.style.fontSize=t.size+'px';p.querySelector('.preview-muted').style.color=t.muted;const b=p.querySelector('.preview-button');b.style.background=t.accent;b.style.color=t.accentText;}
function updateTheme(){let t=selected();if(t.builtIn){t=Object.assign({},t,{id:'custom-'+Date.now(),name:t.name+' Custom',builtIn:false});themes.push(t);currentId=t.id;}t.name=document.getElementById('themeName').value.trim()||'Custom';['background','text','muted','accent','accentText','font'].forEach(k=>t[k]=document.getElementById(k).value);t.size=Number(document.getElementById('size').value);renderOptions();document.getElementById('deleteTheme').disabled=false;renderPreview();}
renderOptions();if(!themes.some(t=>t.id===currentId)){themes.push(Object.assign({},initial.theme,{builtIn:false}));currentId=initial.theme.id;renderOptions();}loadEditor();
themeSelect.onchange=()=>{currentId=themeSelect.value;loadEditor();};fields.forEach(id=>document.getElementById(id).oninput=updateTheme);
document.getElementById('newTheme').onclick=()=>{const base=selected(),id='custom-'+Date.now();themes.push(Object.assign({},base,{id:id,name:'My theme',builtIn:false}));currentId=id;renderOptions();loadEditor();document.getElementById('themeName').focus();};
document.getElementById('deleteTheme').onclick=()=>{const t=selected();if(t.builtIn)return;themes=themes.filter(x=>x.id!==t.id);currentId='classic';renderOptions();loadEditor();};
const paired=Boolean(initial.gatewayToken);if(paired){document.getElementById('pairing').className='hidden';document.getElementById('intro').textContent='Adjust Beepster without pairing again.';document.getElementById('save').textContent='Test connection, save & apply';s.textContent='Your gateway credential remains on the phone.';}
if(typeof initial.refresh==='number')document.getElementById('refresh').value=String(initial.refresh);
f.onsubmit=async(e)=>{e.preventDefault();updateTheme();s.className='hint';s.textContent='Testing…';try{let token=initial.gatewayToken||'';if(token){const test=await fetch('/v1/chats?limit=1',{headers:{authorization:'Bearer '+token}});if(!test.ok)throw new Error('Saved connection failed with '+test.status);}else{const r=await fetch('/pair',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({code:document.getElementById('code').value.trim()})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Pairing failed');token=j.gatewayToken;}const chosen=selected(),custom=themes.filter(t=>!t.builtIn).slice(0,20),quickReplies=[],services=[...serviceContainer.querySelectorAll('input:checked')].map(input=>input.value),savedAppleAliases={};for(let i=0;i<8;i++){const reply=document.getElementById('quickReply'+i).value.trim();if(reply)quickReplies.push(reply);}appleLinks.querySelectorAll('input').forEach(input=>{const alias=input.value.trim();if(alias)savedAppleAliases[input.dataset.chatId]=alias;});const value={gatewayURL:location.origin,gatewayToken:token,theme:chosen,themes:custom,quickReplies:quickReplies,services:services,appleAliases:savedAppleAliases,textSize:chosen.size>=26?'large':'normal',refresh:Number(document.getElementById('refresh').value)};location.href='pebblejs://close#'+encodeURIComponent(JSON.stringify(value));}catch(err){s.className='error';s.textContent=err.message;}};
</script></body></html>`;
}
